### PR TITLE
Added RFC for application/rdf+xml media type

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by tpluscode** [comment]
Is it enough to add the XML file for the RFC spec?

**Comment by dret** [comment]
can you give me write access to this branch? i think github made that very easy now for all PRs.

**Comment by dret** [comment]
never mind. i'll just look at the XML.

**Comment by dret** [comment]
thanks! https://github.com/dret/webconcepts/commit/7a60d4dbe06ebd4e8cd066c0441f3db87a7d425d has the updated/regenerated site, which is live now: http://webconcepts.info/specs/IETF/RFC/3870

**Pull request merged**
